[Incoming]
Protocol = "tcp"
Host = "127.0.0.1"
Port = 1883
Username = "admin"
Password = "public"
Qos = 0
KeepAlive = 3600
MqttClientId = "readsubscriber"
Topic = "DataTopic"

[Response]
Protocol = "tcp"
Host = "127.0.0.1"
Port = 1883
Username = "admin"
Password = "public"
Qos = 0
KeepAlive = 3600
MqttClientId = "ResponseSubscriber"
Topic = "ResponseTopic"